version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/app
    steps:
      - run:
          name: Update and install SSH & Git
          command: apk update && apk upgrade && apk add --no-cache bash git openssh
      - checkout
      - run:
          name: Install npm deployment app
          command: npm install -g github-release-cli
      - deploy:
          name: Create a release
          command: |
            PACKAGE_VERSION=$(cat package.json \
              | grep version \
              | head -1 \
              | awk -F: '{ print $2 }' \
              | sed 's/[",]//g')
            echo "Creating release '${PACKAGE_VERSION}.${CIRCLE_BUILD_NUM}'"

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          context: github-thething
